name: hear_me
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.0.0
  video_player: ^2.4.5
  cupertino_icons: ^1.0.6
  salomon_bottom_bar: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon.png"
flutter:
  uses-material-design: true

  assets:
    - lib/assets/poster1.jpg
    - lib/assets/poster2.jpg
    - lib/assets/poster3.jpg
    - lib/assets/poster4.jpg
    - lib/assets/poster5.jpg
    - lib/assets/poster6.jpg
    - lib/assets/poster7.jpg
    - lib/assets/background.png
